version: '3'

services:
  master:
    image: redis:latest
    container_name: redis-master
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  slave:
    image: redis:latest
    container_name: redis-slave
    command: redis-server --slaveof master 6379 --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6380:6379
    depends_on:
      - master

volumes:
  redis-data:
