rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: #HOST
es_port: 9200
es_username: "#USERNAME"
es_password: "#PASSWORD"
writeback_index: elastalert_status
alert_time_limit:
  days: 2