version: '3'
services:
    redis:
      restart: always
      image: redis:6.0.5
      command: redis-server --requirepass changeme --port 6379
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
